### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ao1Pointblank** [patri9ck/a2ln-server#12]
does not work on linux mint.
```  
File "/usr/local/bin/a2ln", line 135
    match error.errno:
          ^
SyntaxError: invalid syntax
```
removing the code from lines 134-144 helps, so long as you start the server with both ports specified

**Comment by patri9ck** [comment]
Hey,
your Python version is probably too old. At least Python 3.10 is required.

You can check the Python version by using:
```
$ python --version
```

**Comment by Ao1Pointblank** [comment]
i have: Python 3.8.10

**Comment by patri9ck** [comment]
You must upgrade it.
