### ISSUE TITLE
Notifications Not Showing Up

### ISSUE THREAD

**Issue by WilliamLongXYZ** [patri9ck/a2ln-server#13]
I use a decently minimal installation of Artix Linux, and I run stock android, with some settings changed, on a Motorola one 5g UW. I found this app in the fdroid store, and thought it would help me get away from my smartphone. But, after I connected, and pressed "Notification" to test it, the notification doesn't show up in my terminal window, and it doesn't show up as a dunst notification. Any help would be really appreciated.

**Comment by patri9ck** [comment]
Hey, thanks for your issue. Can you link a screenshot of the server's terminal output and a screenshot of the app's "Servers" tab just so I can make sure everything is set up correctly?

**Comment by WilliamLongXYZ** [comment]
Sure!

![image](https://user-images.githubusercontent.com/78674414/191381573-2e4a63be-99dd-4ca4-89fb-4b5aad436eb9.png)
Here's what my desktop shows,

![image](https://user-images.githubusercontent.com/78674414/191382200-de599356-858b-486f-ab2b-0a913d19a0f5.png)
And this is the server tab, when I add the server.

**Comment by patri9ck** [comment]
Interesting, the app says "Pairing failed" for some reason but the server says the pairing is fine.
That means the app and the server are not paired and therefore sending a notification also doesn't work. 
So if you have for some reason Android Studio installed, you can take a look at the app's debug messages. But I will add an option to view the debug messages inside the app so you don't have to use Android Studio.
Right now I have no idea what could be wrong. I will take a further look at this when I'm back home this afternoon.

**Comment by Handis1201** [comment]
To me it looks like a bit fell over in the wrong place

**Comment by patri9ck** [comment]
Sorry for not responding for so long, had a busy week. I'm working on an update that allows you to see some logs for easier debugging.

**Comment by patri9ck** [comment]
Closed because of inactivity.
