### ISSUE TITLE
Does not run on Mint 20.3

### ISSUE THREAD

**Issue by Ao1Pointblank** [patri9ck/a2ln-server#18]
After upgrading python to 3.10.8, I decided to retry a2ln-server, hoping I would not need to cut out lines as stated in error report #12 
However, I still get an error:
![Screenshot from 2022-11-22 19-13-25](https://user-images.githubusercontent.com/88149675/203446638-81313ed6-f646-4c4e-9c8b-9694a8c4060f.png)

I have installed python3-gi and python-gi-dev with apt.

**Comment by Ao1Pointblank** [comment]
Fixed:
install dependencies
```
python3.10 -m pip install pgi setproctitle qrcode zmq pillow
```
(a simple ``pip install`` may also work, instead of specifying python3.10)

then, replace line 30 of /usr/bin/a2ln, "import gi", with:
```
import pgi
pgi.install_as_gi()
from gi.repository import GLib, Gio
```
You also need to scroll down in the file and replace 2 references to "gi" into "pgi":
```
pgi.require_version('Notify', '0.7')

from pgi.repository import Notify
```
And then it should work.

**Comment by patri9ck** [comment]
Thanks for the issue. I will add your solution to the project page incase someone has the same problem.
