### ISSUE TITLE
Python 3.10 required

### ISSUE THREAD

**Issue by vbooka1** [patri9ck/a2ln-server#20]
please consider adjusting the code to support old shi^W^W Enterprise Distributions that have older Python versions installed by default.

```
$ python3.6 a2ln
  File "a2ln", line 118
    match error.errno:
              ^
SyntaxError: invalid syntax
```

**Comment by patri9ck** [comment]
I will try to change it. Which distribution uses Python 3.6?

**Comment by vbooka1** [comment]
> I will try to change it. Which distribution uses Python 3.6?

openSuSE Leap 15.4. 

I confirm that the new version of the script works with Python 3.6, thank you!
