### ISSUE TITLE
Allow specifying a listening address

### ISSUE THREAD

**Issue by ctrl-q** [patri9ck/a2ln-server#22]
We currently can only specify listening ports, but it would be nice to be able to specify a listening address. This way, someone who uses an SSH tunnel for example, could listen only on `tcp://127.0.0.1:<port>` instead of listening on all addresses

**Comment by patri9ck** [comment]
Thanks for the feature request! I will add it in the following days.

**Comment by patri9ck** [comment]
@ctrl-q Could you maybe checkout my branch `custom-addresses` and take a look whether it is a solution to your problem?

**Comment by ctrl-q** [comment]
It's working! But maybe to avoid this being a breaking change, the default address should be * or 0.0.0.0 rather than 127.0.0.1
