### ISSUE TITLE
Dependencies not installed automatically

### ISSUE THREAD

**Issue by Domi04151309** [patri9ck/a2ln-server#3]
After following the guide in the readme this happens

![image](https://user-images.githubusercontent.com/36272047/153480172-f07e7b53-fd18-4fb3-b177-dd8c18a90056.png)

I am not able to install the missing module. Using `pip install <package>` fails too.

**Comment by Domi04151309** [comment]
![image](https://user-images.githubusercontent.com/36272047/153500234-db7cb792-eb64-4541-ab61-e7dcd7c4a6ff.png)
Still the same error message

**Comment by Domi04151309** [comment]
I think it works when I run pip as root. The error did not appear anymore after that.

**Comment by patri9ck** [comment]
Could you install the Python packages without sudo and then run A2LN with a port higher than 1023 (e.g. 5000 as I did)?

**Comment by Domi04151309** [comment]
That works too. I'm a bit new to this kind of software.

**Comment by svdragster** [comment]
> 

Ports below 1024 are reserved
https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html
