### ISSUE TITLE
Not Installing Properly Please Assist 

### ISSUE THREAD

**Issue by rohanbarai-INK** [patri9ck/a2ln-server#40]
so i'm using ubuntu 22.04. i have downloaded the software from git but when i execute the command 

rahul@Asus-Tuf:~/Programs$ ls
a2ln-server
rahul@Asus-Tuf:~/Programs$ cd a2ln-server/
rahul@Asus-Tuf:~/Programs/a2ln-server$ ls
a2ln.service  pypi.md         README.md         src
COPYING       pyproject.toml  requirements.txt
rahul@Asus-Tuf:~/Programs/a2ln-server$ python3 -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/rahul/Programs/a2ln-server
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=13276 sha256=d36bf1573aa82bdcd9bf7ff84ea5352bfe04836909a3ceb2b90e6e757e19b184
  Stored in directory: /home/rahul/.cache/pip/wheels/90/1f/12/353292f6f97710d64a6e70cb4326a36962237055a8cdbbac54
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0

![Screenshot from 2024-04-03 13-32-08](https://github.com/patri9ck/a2ln-server/assets/77430015/6a080dac-7ffa-488e-a72c-5116dfe167b7)

**Comment by patri9ck** [comment]
I'm not sure why Python is naming the package "UNKNOWN". Can you try to install it from PyPI?
```
python -m pip install a2ln
```

**Comment by helpdeskdan** [comment]
Same issue.  "python -m pip install a2ln" works.

**Comment by patri9ck** [comment]
If there are any more issues, feel free to create a new one. Closing this as of now.
