### ISSUE TITLE
Excessive CPU usage after encryption/authentication update

### ISSUE THREAD

**Issue by auroszx** [patri9ck/a2ln-server#6]
Hi. I've been using this project on my laptop for a while, it's very simple and straightforward to use. Thank you for making/maintaining it.

I recently updated both the server (AUR build) and app (through F-Droid) to their latest versions, and noticed the server is stuck at nearly 100% CPU usage all the time. 

I only noticed because my laptop was getting very hot after an upgrade while doing nothing. Here you can see the temps and the CPU usage from a python3 process, and said process belongs to a2ln:

![a2ln-excessive-cpu](https://user-images.githubusercontent.com/5099367/179432135-682bf8c6-a476-411d-9944-3eea3f1c57bc.png)

I'll try not to run it in the meantime for obvious reasons, but please let me know if you need more information to debug it. Have you noticed something like this on your end? Maybe there's something wrong/missing on my end?

Thanks in advanced.

**Comment by alheir** [comment]
Hi!

Same problem here. I just updated both server and app (AUR and F-Droid) and noticed high CPU usage from the server. I'm running Arch with all packages up-to-date, if that helps.

![Screenshot from 2022-07-17 23-46-05](https://user-images.githubusercontent.com/99462480/179438423-e115edad-4aab-4c3f-80bf-d9d5f1e9f051.png)

**Comment by patri9ck** [comment]
Hey, thanks for your issue. Seems like the while loop is causing the issue. I will continue debugging when I'm home.

**Comment by patri9ck** [comment]
I guess the issue is fixed, I created a new release and updated the AUR package (in case you use Arch Linux). For some reason, a simple Python script like this would cause the exact same issue:
```python
while True:
    pass
```
I'm not used to this behavior from other programming languages but I fixed it by adding a sleep statement. Thanks for reporting the issue.
