### ISSUE TITLE
Add argument for pairing port

### ISSUE THREAD

**Issue by jonas-w** [patri9ck/a2ln-server#7]
1. Works great so far!
2. Only issue i had was the random pairing port.
- I have a firewall running
- Due to the port being random i needed to disable my firewall temporarily

People who use a firewall too, may be interested in having this as an optional argument.

**Comment by patri9ck** [comment]
Oh, that is something I totally did not think of. I will add an optional argument to specify the pairing port.

**Comment by patri9ck** [comment]
See #9
